# Generated by Django 3.0.5 on 2020-04-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_auto_20200413_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
